Test slack alert channel

diff --git a/.github/workflows/update-snapshot.yml b/.github/workflows/update-snapshot.yml
--- a/.github/workflows/update-snapshot.yml
+++ b/.github/workflows/update-snapshot.yml
@@ -1,79 +1,82 @@
 name: Update to new data snapshot (regenerate colors and sharing images).
 
 on:
+  push:
   repository_dispatch:
     types: update-data-snapshot
 
 env:
   AWS_S3_BUCKET: content.covidactnow.org
-  BRANCH: ${{ github.event.client_payload.branch }}
-  SNAPSHOT_ID: ${{ github.event.client_payload.snapshot_id }}
+  BRANCH: develop # ${{ github.event.client_payload.branch }}
+  SNAPSHOT_ID: 234 # ${{ github.event.client_payload.snapshot_id }}
   # Used in the shared images URL and in the PR branch.
-  RUN_ID: ${{ github.event.client_payload.snapshot_id }}-${{github.run_number}}
+  RUN_ID: 2456  #${{ github.event.client_payload.snapshot_id }}-${{github.run_number}}
+  DEPLOY_SLACK_CHANNEL: test-dev-alerts
 
 jobs:
   update-data-snapshot:
-    runs-on: [self-hosted, cpu-optimized]
+    runs-on: ubuntu-latest  # [self-hosted, cpu-optimized]
     steps:
       # Setup
       - name: Verify snapshot provided
         if: ${{ !env.SNAPSHOT_ID }}
         run: 'echo "Missing client_payload parameter: snapshot_id" ; exit 1'
-      - name: Verify branch provided
-        if: ${{ !env.BRANCH }}
-        run: 'echo "Missing client_payload parameter: branch" ; exit 1'
-      - uses: actions/checkout@v2
-        with:
-          repository: covid-projections/covid-projections
-          ref: '${{ env.BRANCH }}'
-      - uses: actions/setup-node@v1
-        with:
-          node-version: 12.x
+      # - name: Verify branch provided
+      #   if: ${{ !env.BRANCH }}
+      #   run: 'echo "Missing client_payload parameter: branch" ; exit 1'
+      # - uses: actions/checkout@v2
+      #   with:
+      #     repository: covid-projections/covid-projections
+      #     ref: '${{ env.BRANCH }}'
+      # - uses: actions/setup-node@v1
+      #   with:
+      #     node-version: 12.x
 
-      # Update snapshot URL and regenerate map colors.
-      - run: yarn install
-      - run: 'echo "{ \"data_url\": \"https://data.covidactnow.org/snapshot/${{env.SNAPSHOT_ID}}/\" }" | python -mjson.tool > src/assets/data/data_url.json'
-      - run: yarn update-location-summaries
+      # # Update snapshot URL and regenerate map colors.
+      # - run: yarn install
+      # - run: 'echo "{ \"data_url\": \"https://data.covidactnow.org/snapshot/${{env.SNAPSHOT_ID}}/\" }" | python -mjson.tool > src/assets/data/data_url.json'
+      # - run: yarn update-location-summaries
 
-      # Generate Share Images and Upload to S3
-      - run: yarn serve -l 3000 &
-      - run: npx wait-on -t 120000 http://localhost:3000/
-      - run: yarn generate-share-images
-      - uses: jakejarvis/s3-sync-action@master
-        with:
-          args: '--acl public-read --follow-symlinks --delete'
-        env:
-          #TODO(michael): Make default secrets work.
-          #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
-          #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.CONTENT_AWS_ACCESS_KEY }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.CONTENT_AWS_SECRET_ACCESS_KEY }}
-          SOURCE_DIR: scripts/generate_share_images/output
-          DEST_DIR: share/${{env.RUN_ID}}
-      - run: 'echo "{ \"share_image_url\": \"https://content.covidactnow.org/share/${{env.RUN_ID}}/\" }" | python -mjson.tool > src/assets/data/share_images_url.json'
+      # # Generate Share Images and Upload to S3
+      # - run: yarn serve -l 3000 &
+      # - run: npx wait-on -t 120000 http://localhost:3000/
+      # - run: yarn generate-share-images
+      # - uses: jakejarvis/s3-sync-action@master
+      #   with:
+      #     args: '--acl public-read --follow-symlinks --delete'
+      #   env:
+      #     #TODO(michael): Make default secrets work.
+      #     #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+      #     #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #     AWS_ACCESS_KEY_ID: ${{ secrets.CONTENT_AWS_ACCESS_KEY }}
+      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.CONTENT_AWS_SECRET_ACCESS_KEY }}
+      #     SOURCE_DIR: scripts/generate_share_images/output
+      #     DEST_DIR: share/${{env.RUN_ID}}
+      # - run: 'echo "{ \"share_image_url\": \"https://content.covidactnow.org/share/${{env.RUN_ID}}/\" }" | python -mjson.tool > src/assets/data/share_images_url.json'
 
-      # Generate Pull Request
-      - name: Create Pull Request
-        uses: peter-evans/create-pull-request@v2
-        with:
-          branch: 'bump-snapshot-${{env.RUN_ID}}'
-          commit-message: |
-            Update to data snapshot ${{env.SNAPSHOT_ID}}.
+      # # Generate Pull Request
+      # - name: Create Pull Request
+      #   uses: peter-evans/create-pull-request@v2
+      #   with:
+      #     branch: 'bump-snapshot-${{env.RUN_ID}}'
+      #     commit-message: |
+      #       Update to data snapshot ${{env.SNAPSHOT_ID}}.
 
-            * Regenerate summary files.
-            * Point at updated share images.
-          title: Update to data snapshot ${{env.SNAPSHOT_ID}}
-          body: |
-            Update to data snapshot ${{env.SNAPSHOT_ID}}.
+      #       * Regenerate summary files.
+      #       * Point at updated share images.
+      #     title: Update to data snapshot ${{env.SNAPSHOT_ID}}
+      #     body: |
+      #       Update to data snapshot ${{env.SNAPSHOT_ID}}.
 
-            * Regenerate summary files.
-            * Point at updated share images.
+      #       * Regenerate summary files.
+      #       * Point at updated share images.
 
       - name: Slack notification
         if: job.status != 'success'
         env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           STATUS: ${{job.status}}
+          SLACK_CHANNEL: ${{ env.DEPLOY_SLACK_CHANNEL }}
         uses: Ilshidur/action-slack@fb92a78
         with:
           args: 'update-snapshot failed: {{STATUS}}'
@@ -82,6 +85,7 @@ jobs:
         env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           STATUS: ${{job.status}}
+          SLACK_CHANNEL: ${{ env.DEPLOY_SLACK_CHANNEL }}
         uses: Ilshidur/action-slack@fb92a78
         with:
           args: |
